options:
  ceph-source:
    type: string
    default: http://ceph.com/debian-hammer main
    description: |
      Optional configuration to support use of additional sources such as:

        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main

      The last option should be used in conjunction with the key configuration
      option.

      Note that a minimum ceph version of 0.48.2 is required for use with this
      charm which is NOT provided by the packages in the main Ubuntu archive
      for precise but is provided in the Ubuntu cloud archive.
  ceph-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
  rabbit-user:
    default: vsm
    type: string
    description: Username to request access on rabbitmq-server.
  rabbit-vhost:
    default: vsm
    type: string
    description: RabbitMQ virtual host to request access on rabbitmq-server.
  database-user:
    default: vsm
    type: string
    description: Username to request database access.
  database:
    default: vsm
    type: string
    description: Database to request access.
  authorized-keys-path:
    type: string
    default: '{homedir}/.ssh/authorized_keys'
    description: |
      Only used when migration-auth-type is set to ssh.
      .
      Full path to authorized_keys file, can be useful for systems with
      non-default AuthorizedKeysFile location. It will be formatted using the
      following variables:
      .
        homedir - user's home directory
        username - username
      .
